# Generated by Django 3.1.6 on 2021-02-13 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0003_auto_20210213_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='keyphrase',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
